(** Automatically generated meta-informations about the project and its building. *)
(* This file is automatically generated; please don't edit it. *)

let name = "intelligence2";;
let version = "trunk";;
let prefix = "/usr/local";;
let ocaml_libraryprefix = "/home/john/.opam/3.12.1/lib/ocaml";;
let libraryprefix = "/home/john/.opam/3.12.1/lib";;
let configurationprefix = "/etc";;
let localeprefix = "/usr/local/share/locale";;
let documentationprefix = "/usr/local/share/doc";;
let uname = "Linux 3.2.0-65-generic #98-Ubuntu SMP Wed Jun 11 20:27:07 UTC 2014 x86_64 GNU/Linux";;
let build_date = "2014-07-23 11:47:32 +0200";;
let revision = "0.0.1";;
